question = '''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

target = 4000000


def fibonacci(n):
    if n < 1: return n
    if n == 1: return 2
    return 4 * fibonacci(n - 1) + fibonacci(n - 2)


def solution():
    i = 1
    x = 0
    _sum = 0
    while x < target:
        _sum += x
        x = fibonacci(i)
        i += 1
    print(_sum)
